# site properties and page defaults
title: VCNC Lab
subtitle: 
description: Welcome! We are the VCNC Lab directed by Dr. Fabian Soto and located at Florida International University in Miami, FL. 
header: images/background.jpg
footer: images/background.jpg
proofer: false

# site social media and other links
links:
  email: fasoto@fiu.edu
  orcid: 0000-0002-1001-679X
  google-scholar: Bb4kyNwAAAAJ
  github: fsotoc
  bluesky: ccnlab.bsky.social
  youtube: channel/UCR0iNPuHA6yqnKBLfWkrycQ

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
