# remove bad entries
- id: doi:10.1101/254995
  remove: true

- id: issn:0120-0534
  remove: true


# add elements to orcid-generated entries

# Hays & Soto, 2024. CBB
- id: doi:10.1007/s42113-024-00227-3
  image: https://pbs.twimg.com/media/EUiOF-0X0AMwfB_?format=png&name=small

# Kia Hosseini et al., 2024, CABN errors
- id: pmid:38839717
  image: images/research/eeg-theta-error.png
  buttons:
    - type: pdf
      link: https://www.biorxiv.org/content/10.1101/2023.09.14.557662v1.full.pdf
    - type: data
      link: https://github.com/NDCLab/memory-for-error-mini

# Hosseini Soto, Emotion, 2024
- id: pmid:38557028
  image: https://pbs.twimg.com/media/GC95oBgWcAAXvk5?format=jpg&name=large
  publisher: Emotion
  buttons:
    - type: pdf
      link: https://osf.io/vfhk9/download/
    - type: data
      link: https://osf.io/thjkq/files/osfstorage?view_only=e17041f72471468993a0444d968c1e27


# encoding models chapter
- id: doi:10.1017/9781108902724.011
  image: https://pbs.twimg.com/media/FUl04epXsAMwzF1?format=png&name=small
  buttons:
    - type: pdf
      link: pdf/chapter12V8.pdf

# Martin et al., 2024. PB&R
- id: pmid:38381300
  image: https://pbs.twimg.com/media/FbmAcOzX0AEkrra?format=png&name=small
  buttons:
    - type: pdf
      link: https://osf.io/jfy93/download/
    - type: data
      link: https://osf.io/ur3wm/files/osfstorage
    - type: preregistration
      link: https://osf.io/ud7jg

# Soto & Beevers, 2024, BP
- id: pmid:38336169
  image: images/research/bp2024.png
  buttons:
    - type: pdf
      link: https://labs.la.utexas.edu/beevers/files/2024/10/Soto-and-Beevers-2024-Perceptual-Observer-Modeling-Reveals-Likely-Mechanisms-of-Face-Expression-Recognition-Deficits-in-Depression.pdf
    - type: highlight
      link: https://www.biologicalpsychiatrycnni.org/article/S2451-9022(24)00114-9/abstract


# Soto et al., RW influence
- id: pmid:37473985
  image: images/research/rw-influence.png
  buttons:
    - type: pdf
      link: https://cicc.utalca.cl/site-assets/uploads/2023/07/soto2023.pdf

# Soto & Narasiwodeyar, 2023, PCB
- id: pmc:PMC9894561
  link: https://doi.org/10.1371/journal.pcbi.1010819
  image: images/research/specificity-invariance.png
  buttons:
    - type: pdf
      link: https://journals.plos.org/ploscompbiol/article/file?id=10.1371/journal.pcbi.1010819&type=printable
    - type: data
      link: https://osf.io/z2h9w/

# Pournaghdali et al., 2022, PBR
- id: pmid:36163609
  image: https://pbs.twimg.com/media/EANDBhIUYAA8OVX?format=png&name=900x900
  buttons:
    - type: pdf
      link: https://osf.io/akem2/download/
    - type: data
      link: https://osf.io/tnx3w/

# Perez et al., 2022, 
- id: pmid:35710303
  image: https://learnmem.cshlp.org/content/29/7/F1.medium.gif
  link: https://learnmem.cshlp.org/content/29/7/160
  buttons:
    - type: pdf
      link: https://learnmem.cshlp.org/content/29/7/160.full.pdf+html


# Soto ... Beevers, 2021, JAP
- id: pmid:34472882
  image: https://pbs.twimg.com/media/FRnjtMVXEAA52qN?format=jpg&name=large
  buttons:
    - type: pdf
      link: https://osf.io/9gxmy/download/

# Hays et al., 2020, FaReT
- id: pmid:32519291
  image: images/research/faret-faces.png
  buttons:
    - type: pdf
      link: https://osf.io/jb53v/download/
    - type: source
      link: https://github.com/fsotoc/FaReT

# Soto et al., 2020, JOV
- id: pmid:33064122
  image: https://pbs.twimg.com/media/ElHW4mXWMAAJpM6?format=png&name=small
  link: https://doi.org/10.1167/jov.20.10.18
  buttons:
    - type: pdf
      link: https://jov.arvojournals.org/arvo/content_public/journal/jov/938495/i1534-7362-20-10-18_1602851973.89623.pdf

# Perez et al., QJEP, 2020
- id: pmid:31931662
  image: https://pbs.twimg.com/media/Dtx9WTQX4AI6LtW?format=jpg&name=small
  buttons:
    - type: pdf
      link: https://osf.io/yx8m4/download/

# Soto, 2019, beyond conceptual system
- id: pmid:31381986
  image: images/research/inhibited-elements.png
  buttons:
    - type: pdf
      link: https://osf.io/mch9n/download/

# Soto, 2019, APP
- id: pmid:31152373
  image: https://pbs.twimg.com/media/Dx0KIqmWoAAEhqk?format=jpg&name=medium
  buttons:
    - type: pdf
      link: https://osf.io/uep7c/download/
    - type: data
      link: https://osf.io/dy23v/

# Soto and Ashby, 2019, psych res
- id: pmid:30806809
  image: https://pbs.twimg.com/media/DXPaTfXXUAETh2K?format=jpg&name=small
  buttons:
    - type: pdf
      link: https://osf.io/9ady5/download/

# Perez et al., 2019, QJEP
- id: pmid:27894212
  date: '2019'
  image: images/research/perez-schedules.png
  publisher: Quarterly Journal of Experimental Psychology
  buttons:
    - type:pdf
      link: pdf/QJEP.19.pazaud.pdf

# Soto et al., 2018, PLOS CB
- id: pmid:30273337
  link: https://doi.org/10.1371/journal.pcbi.1006470
  image: images/research/neurogrt.png
  buttons:
    - type: pdf
      link: https://journals.plos.org/ploscompbiol/article/file?id=10.1371/journal.pcbi.1006470&type=printable
    - type: data
      link: https://osf.io/qrupw/?view_only=e9ed7b7dcbfb41ea8b302e84548d8d6a

# Soto, 2018, JEPG blocking
- id: pmid:29698030
  image: images/research/similarity-blocking.png
  buttons:
    - type: pdf
      link: pdf/JEPG.17.s.pdf

# Perez et al., 2018, exp psych
- id: pmid:30165807
  image: images/research/summation-everywhere.png
  buttons:
    - type: pdf
      link: pdf/EP.18.pss.pdf

# Soto et al., 2017, grtools
- id: pmc:PMC5440596
  link: https://doi.org/10.3389/fpsyg.2017.00696
  image: https://www.frontiersin.org/files/Articles/236046/fpsyg-08-00696-HTML/image_m/fpsyg-08-00696-g002.jpg
  buttons:
    - type: pdf
      link: https://www.frontiersin.org/journals/psychology/articles/10.3389/fpsyg.2017.00696/pdf
    - type: source
      link: https://github.com/fsotoc/grtools

# Soto et al., 2016
- id: pmid:27453156
  buttons:
    - type: pdf
      link: pdf/NIMG.16.sba.pdf

# Ashby Soto, 2016, grtneuro
- title: The neural basis of general recognition theory
  authors:
  - Fabian A. Soto
  - F. Gregory Ashby
  publisher: "Mathematical models of perception and cognition, Volume II: A festschrift for James T. Townsend"
  date: '2016-04-30'
  link: https://www.taylorfrancis.com/chapters/edit/10.4324/9781315647265-1/neural-basis-general-recognition-theory-gregory-ashby-fabian-soto
  buttons:
  - type: pdf
    link: pdf/GRT-neuro.pdf

# Soto Wasserman, 2016, BP
- id: pmid:26608549
  date: '2016-02-01'
  buttons:
  - type: pdf
    link: pdf/BP.15.sw.pdf

# Soto et al., 2015, Cognit
- id: pmid:26163820
  buttons:
  - type: pdf
    link: pdf/COGN.15.sqppv.pdf

# Soto Ashby, 2015, Cognit
- id: pmid:25817370
  buttons:
  - type: pdf
    link: pdf/COGN.15.sa.pdf

# Soto et al., 2015, PBR
- id: pmid:24841236
  buttons:
  - type: pdf
    link: pdf/PBR.14.svma.pdf

# Ashby Soto, 2015, GRT review
- id: https://doi.org/10.1093/oxfordhb/9780199957996.013.2
  buttons:
  - type: pdf
    link: pdf/GRT_SS.pdf

# Soto Wasserman, 2014, frontiers neural circuits
- id: pmid:25352784
  image: images/research/evolutionary-atomism.jpg
  link: https://doi.org/10.3389/fncir.2014.00122
  buttons:
  - type: pdf
    link: https://www.frontiersin.org/journals/neural-circuits/articles/10.3389/fncir.2014.00122/pdf

# Soto et al., 2014, psych review
- id: pmid:25090430
  buttons:
  - type: pdf
    link: pdf/PR.14.sgn.pdf

# Soto et al., 2013, NIMG
- id: pmid:23333700
  buttons:
  - type: pdf
    link: pdf/NIMG.13.swha.pdf

# Soto, Siow, Wasserman, 2012, V Res
- id: pmid:22531015
  buttons:
  - type: pdf
    link: pdf/VR.12.ssw.pdf

# Soto, Wasserman, 2012, overshadowing
- id: pmid:22823423
  buttons: 
  - type: pdf
    link: pdf/JEPABP.12.sw.pdf

# Soto Wasserman, 2012, CABN
- id: pmid:22086545
  buttons:
  - type: pdf
    link: pdf/CABN.12.sw.pdf

# Soto Wasserman, 2011, JOV
- id: pmid:21454855
  link: https://doi.org/10.1167/11.3.24
  buttons:
  - type: pdf
    link: https://jov.arvojournals.org/arvo/content_public/journal/jov/933483/jov-11-3-24.pdf

# Soto Wasserman, 2010, Psych sci
- id: pmid:20817911
  buttons:
  - type: pdf
    link: pdf/PS.10.sw.pdf

# Lazareva et al., 2010, BP
- id: pmid:20600696
  buttons:
  - type: pdf
    link: pdf/BP.10.lsw.pdf

# Soto Wasserman, 2010, JEPABP
- id: pmid:20384400
  buttons:
  - type: pdf
    link: pdf/ABP.10.sw.pdf

# Soto Wasserman, 2010, PR
- id: pmid:20438230
  buttons:
  - type: pdf
    link: pdf/PR.10.sw.pdf

# Soto Wasserman, 2010, commentary
- id: pmid:20824149
  buttons:
  - type: pdf
    link: pdf/vol_5_commentary_sotowasserman.pdf

# Soto et al., 2009, QJEP
- id: pmid:19048450
  buttons:
  - type: pdf
    link: pdf/QJEP.09.svcw.pdf