- id: pmid:35710303
  image: https://learnmem.cshlp.org/content/29/7/F1.medium.gif
  link: https://learnmem.cshlp.org/content/29/7/160
  tags:
    - generalization

- id: doi:10.1007/s42113-024-00227-3
  image: https://pbs.twimg.com/media/EUiOF-0X0AMwfB_?format=png&name=small

- id: doi:10.1101/254995
  remove: true

- id: pmid:38557028
  image: https://pbs.twimg.com/media/GC95oBgWcAAXvk5?format=jpg&name=large
  publisher: Emotion

- id: doi:10.1017/9781108902724.011
  image: https://pbs.twimg.com/media/FUl04epXsAMwzF1?format=png&name=small